// Cloud-Init Configuration Module
// Generates cloud-init YAML with all necessary files encoded

@description('Domain name for n8n')
param domainName string

@description('n8n version')
param n8nVersion string

@description('n8n encryption key')
@secure()
param n8nEncryptionKey string

@description('Admin username')
param adminUsername string

@description('TLS email for Let\'s Encrypt')
param tlsEmail string = 'admin@${domainName}'

@description('Environment')
param environment string = 'production'

// ============================================================================
// Load Container Configuration Files
// ============================================================================

// Docker Compose
var dockerComposeYaml = loadTextContent('../containers/docker-compose.yml')

// n8n environment template
var n8nEnvTemplate = loadTextContent('../containers/n8n/n8n.env.template')

// Caddyfile
var caddyfileTemplate = loadTextContent('../containers/caddy/caddy.template')

// Caddy environment template
var caddyEnvTemplate = loadTextContent('../containers/caddy/caddy.env.template')

// Deployment script
var deployScript = loadTextContent('../containers/scripts/deploy.sh')

// Backup script
var backupScript = loadTextContent('../containers/scripts/backup.sh')

// Health check script
var healthCheckScript = loadTextContent('../containers/scripts/health-check.sh')

// ============================================================================
// Variable Substitution
// ============================================================================

// Replace placeholders in Caddyfile
var caddyfile = replace(
  replace(
    caddyfileTemplate,
    '{{DOMAIN_NAME}}', domainName),
  '{{TLS_EMAIL}}', tlsEmail)

// Replace placeholders in n8n env template
var n8nEnv = replace(
  replace(
    replace(
      replace(
        replace(
          n8nEnvTemplate,
          '{{DOMAIN_NAME}}', domainName),
        '{{N8N_VERSION}}', n8nVersion),
      '{{ENCRYPTION_KEY}}', n8nEncryptionKey),
    '{{TLS_EMAIL}}', tlsEmail),
  '{{ENVIRONMENT}}', environment)

// Replace placeholders in Caddy env template
var caddyEnv = replace(
  replace(
    caddyEnvTemplate,
    '{{DOMAIN_NAME}}', domainName),
  '{{TLS_EMAIL}}', tlsEmail)

// Indent rendered text for YAML block scalars
var dockerComposeText = replace(dockerComposeYaml, '\n', '\n      ')
var n8nEnvText = replace(n8nEnv, '\n', '\n      ')
var caddyfileText = replace(caddyfile, '\n', '\n      ')
var caddyEnvText = replace(caddyEnv, '\n', '\n      ')
var deployScriptText = replace(deployScript, '\n', '\n      ')
var backupScriptText = replace(backupScript, '\n', '\n      ')
var healthCheckScriptText = replace(healthCheckScript, '\n', '\n      ')

// Explicit reference so the analyzer sees these template sources as used
var templateSourceCount = length([
  dockerComposeYaml
  n8nEnvTemplate
  caddyfileTemplate
  caddyEnvTemplate
  deployScript
  backupScript
  healthCheckScript
  caddyfile
  n8nEnv
  caddyEnv
  dockerComposeText
  n8nEnvText
  caddyfileText
  caddyEnvText
  deployScriptText
  backupScriptText
  healthCheckScriptText
])

// ============================================================================
// Base64 Encode Files for Cloud-Init
// ============================================================================

// ============================================================================
// Generate Cloud-Init Configuration
// ============================================================================

var cloudInitTemplate = '''
#cloud-config

# n8n Automated Deployment
# Generated by Bicep template

package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - jq
  - sqlite3
  - unattended-upgrades

write_files:
  # ============================================================================
  # Container Configuration
  # ============================================================================
  
  - path: /opt/n8n/docker-compose.yml
    content: |
      __DOCKER_COMPOSE_TEXT__
    owner: root:root
    permissions: '0644'

  - path: /opt/n8n/.env
    content: |
      __N8N_ENV_TEXT__
    owner: root:root
    permissions: '0600'
  
  - path: /opt/n8n/caddy/Caddyfile
    content: |
      __CADDYFILE_TEXT__
    owner: root:root
    permissions: '0644'

  - path: /opt/n8n/caddy/.env
    content: |
      __CADDY_ENV_TEXT__
    owner: root:root
    permissions: '0600'
  
  # ============================================================================
  # Operational Scripts
  # ============================================================================
  
  - path: /opt/n8n/scripts/deploy.sh
    content: |
      __DEPLOY_SCRIPT_TEXT__
    owner: root:root
    permissions: '0755'
  
  - path: /opt/n8n/scripts/backup.sh
    content: |
      __BACKUP_SCRIPT_TEXT__
    owner: root:root
    permissions: '0755'
  
  - path: /opt/n8n/scripts/health-check.sh
    content: |
      __HEALTH_CHECK_SCRIPT_TEXT__
    owner: root:root
    permissions: '0755'
  
  # ============================================================================
  # Systemd Service for n8n
  # ============================================================================
  
  - path: /etc/systemd/system/n8n.service
    content: |
      [Unit]
      Description=n8n Workflow Automation
      Requires=docker.service
      After=docker.service
      
      [Service]
      Type=oneshot
      RemainAfterExit=yes
      WorkingDirectory=/opt/n8n
      ExecStart=/usr/bin/docker compose up -d
      ExecStop=/usr/bin/docker compose down
      ExecReload=/usr/bin/docker compose restart
      
      [Install]
      WantedBy=multi-user.target
    owner: root:root
    permissions: '0644'
  
  # ============================================================================
  # Systemd Timer for Backups
  # ============================================================================
  
  - path: /etc/systemd/system/n8n-backup.service
    content: |
      [Unit]
      Description=n8n Backup Service
      
      [Service]
      Type=oneshot
      ExecStart=/opt/n8n/scripts/backup.sh
      StandardOutput=journal
      StandardError=journal
    owner: root:root
    permissions: '0644'
  
  - path: /etc/systemd/system/n8n-backup.timer
    content: |
      [Unit]
      Description=n8n Backup Timer (Daily at 2 AM)
      
      [Timer]
      OnCalendar=daily
      OnCalendar=02:00
      Persistent=true
      
      [Install]
      WantedBy=timers.target
    owner: root:root
    permissions: '0644'
  
  # ============================================================================
  # Systemd Timer for Health Checks
  # ============================================================================
  
  - path: /etc/systemd/system/n8n-health.service
    content: |
      [Unit]
      Description=n8n Health Check Service
      
      [Service]
      Type=oneshot
      ExecStart=/opt/n8n/scripts/health-check.sh
      StandardOutput=journal
      StandardError=journal
    owner: root:root
    permissions: '0644'
  
  - path: /etc/systemd/system/n8n-health.timer
    content: |
      [Unit]
      Description=n8n Health Check Timer (Every 5 minutes)
      
      [Timer]
      OnBootSec=5min
      OnUnitActiveSec=5min
      
      [Install]
      WantedBy=timers.target
    owner: root:root
    permissions: '0644'
  
  # ============================================================================
  # Logrotate Configuration
  # ============================================================================
  
  - path: /etc/logrotate.d/n8n
    content: |
      /var/log/n8n/*.log {
          daily
          rotate 14
          compress
          delaycompress
          notifempty
          create 0644 root root
          sharedscripts
          postrotate
              systemctl reload n8n > /dev/null 2>&1 || true
          endscript
      }
      
      /var/log/caddy/*.log {
          daily
          rotate 14
          compress
          delaycompress
          notifempty
          create 0644 root root
      }
    owner: root:root
    permissions: '0644'
  
  # ============================================================================
  # Monitoring Script
  # ============================================================================
  
  - path: /opt/n8n/scripts/monitor.sh
    content: |
      #!/bin/bash
      # Quick status check
      
      echo "=== n8n Status ==="
      systemctl status n8n --no-pager
      
      echo ""
      echo "=== Container Status ==="
      docker compose -f /opt/n8n/docker-compose.yml ps
      
      echo ""
      echo "=== Recent Logs ==="
      docker logs n8n --tail 20
    owner: root:root
    permissions: '0755'

runcmd:
  # ============================================================================
  # Initialization
  # ============================================================================
  
  - echo "=========================================="
  - echo "n8n Deployment Started"
  - 'echo "Time: $(date)"'
  - 'echo "Domain: __DOMAIN_NAME__"'
  - 'echo "Version: __N8N_VERSION__"'
  - echo "=========================================="
  
  # ============================================================================
  # Install Docker
  # ============================================================================
  
  - echo "📦 Installing Docker..."
  - curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
  - sh /tmp/get-docker.sh
  - usermod -aG docker __ADMIN_USERNAME__
  - systemctl enable docker
  - systemctl start docker
  - echo "✅ Docker installed"
  
  # ============================================================================
  # Install Docker Compose
  # ============================================================================
  
  - echo "📦 Installing Docker Compose..."
  - mkdir -p /usr/local/lib/docker/cli-plugins
  - curl -SL https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
  - chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
  - docker compose version
  - echo "✅ Docker Compose installed"
  
  # ============================================================================
  # Create Directory Structure
  # ============================================================================
  
  - echo "📁 Creating directory structure..."
  - mkdir -p /opt/n8n/caddy /opt/n8n/n8n /opt/n8n/backups /opt/n8n/scripts
  - mkdir -p /var/log/n8n /var/log/caddy
  - mkdir -p /opt/n8n/caddy/logs
  - chown -R __ADMIN_USERNAME__:__ADMIN_USERNAME__ /opt/n8n
  - chown -R __ADMIN_USERNAME__:__ADMIN_USERNAME__ /var/log/n8n
  - echo "✅ Directories created"
  
  # ============================================================================
  # Deploy n8n
  # ============================================================================
  
  - echo "🚀 Deploying n8n..."
  - cd /opt/n8n
  - sudo -u root /opt/n8n/scripts/deploy.sh
  - echo "✅ n8n deployed"
  
  # ============================================================================
  # Enable Systemd Services
  # ============================================================================
  
  - echo "⚙️  Enabling systemd services..."
  - systemctl daemon-reload
  - systemctl enable n8n.service
  - systemctl enable n8n-backup.timer
  - systemctl enable n8n-health.timer
  - systemctl start n8n-backup.timer
  - systemctl start n8n-health.timer
  - echo "✅ Systemd services enabled"
  
  # ============================================================================
  # Configure Automatic Updates
  # ============================================================================
  
  - echo "🔄 Configuring automatic updates..."
  - 'echo "unattended-upgrades unattended-upgrades/enable_auto_updates boolean true" | debconf-set-selections'
  - DEBIAN_FRONTEND=noninteractive dpkg-reconfigure -f noninteractive unattended-upgrades || true
  - echo "✅ Automatic updates configured"
  
  # ============================================================================
  # Post-Deployment Verification
  # ============================================================================
  
  - echo "🔍 Verifying deployment..."
  - sleep 30
  - docker ps -a
  - docker logs n8n --tail 50
  - docker logs caddy --tail 50
  
  # ============================================================================
  # Create Status Files
  # ============================================================================
  
  - |
    cat > /opt/n8n/deployment-status.txt << EOFSTATUS
    Deployment Status
    =================
    
    Completed: $(date)
    Domain: __DOMAIN_NAME__
    n8n Version: __N8N_VERSION__
    Environment: __ENVIRONMENT__
    Admin User: __ADMIN_USERNAME__
    
    Container Status:
    $(docker ps -a)
    
    Access:
    - URL: https://__DOMAIN_NAME__
    - SSH: ssh __ADMIN_USERNAME__@$(hostname -I | awk '{print $1}')
    
    Logs:
    - n8n: docker logs n8n
    - Caddy: docker logs caddy
    - Deployment: /var/log/cloud-init-output.log
    
    Scripts:
    - Backup: /opt/n8n/scripts/backup.sh
    - Health Check: /opt/n8n/scripts/health-check.sh
    - Monitor: /opt/n8n/scripts/monitor.sh
    
    Systemd Services:
    - n8n.service (main service)
    - n8n-backup.timer (daily backups)
    - n8n-health.timer (health checks)
    EOFSTATUS
  
  # ============================================================================
  # Final Message
  # ============================================================================
  
  - echo "=========================================="
  - echo "✅ n8n Deployment Complete!"
  - echo "=========================================="
  - echo ""
  - 'echo "📋 Deployment Summary:"'
  - cat /opt/n8n/deployment-status.txt
  - echo ""
  - 'echo "🌐 Next Steps:"'
  - echo "1. Configure DNS A record to point to this server"
  - echo "2. Wait 5-10 minutes for SSL certificate"
  - 'echo "3. Access n8n at: https://__DOMAIN_NAME__"'
  - echo ""
  - 'echo "📊 Useful Commands:"'
  - 'echo "  - View status: /opt/n8n/scripts/monitor.sh"'
  - 'echo "  - View logs: docker logs n8n -f"'
  - 'echo "  - Backup now: /opt/n8n/scripts/backup.sh"'
  - 'echo "  - Health check: /opt/n8n/scripts/health-check.sh"'
  - echo ""

final_message: |
  n8n deployment complete!
  
  Access your instance at: https://__DOMAIN_NAME__
  
  View deployment status: cat /opt/n8n/deployment-status.txt
  Monitor containers: /opt/n8n/scripts/monitor.sh
'''

var cloudInitConfig = replace(
  replace(
    replace(
      replace(
        replace(
          replace(
            replace(
              replace(
                replace(
                  replace(
                    replace(
                      replace(
                        cloudInitTemplate,
                        '__DOCKER_COMPOSE_TEXT__', dockerComposeText),
                      '__N8N_ENV_TEXT__', n8nEnvText),
                    '__CADDYFILE_TEXT__', caddyfileText),
                  '__CADDY_ENV_TEXT__', caddyEnvText),
                '__DEPLOY_SCRIPT_TEXT__', deployScriptText),
              '__BACKUP_SCRIPT_TEXT__', backupScriptText),
            '__HEALTH_CHECK_SCRIPT_TEXT__', healthCheckScriptText),
          '__DOMAIN_NAME__', domainName),
        '__N8N_VERSION__', n8nVersion),
      '__ENVIRONMENT__', environment),
    '__ADMIN_USERNAME__', adminUsername),
  '__TLS_EMAIL__', tlsEmail)

// ============================================================================
// Outputs
// ============================================================================

@description('Base64-encoded cloud-init configuration')
output cloudInitBase64 string = base64(cloudInitConfig)

@description('Plain text cloud-init configuration (for debugging)')
output cloudInitPlain string = cloudInitConfig

@description('Container files summary')
output filesIncluded object = {
  dockerCompose: 'docker-compose.yml'
  caddyfile: 'Caddyfile'
  deployScript: 'deploy.sh'
  backupScript: 'backup.sh'
  healthCheckScript: 'health-check.sh'
  systemdServices: [
    'n8n.service'
    'n8n-backup.service'
    'n8n-backup.timer'
    'n8n-health.service'
    'n8n-health.timer'
  ]
}

@description('Configuration summary')
output configSummary object = {
  domain: domainName
  n8nVersion: n8nVersion
  adminUser: adminUsername
  tlsEmail: tlsEmail
  environment: environment
  templateSourceCount: templateSourceCount
}
